import { StyleSheet } from 'react-native';
import { FONT_SIZES } from '../../utils/FontSize';
import { Font_Family } from '../../utils/Fontfamily';
import { Colors } from '../../utils/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'white', paddingHorizontal: 15 },
  heading: {
    paddingTop: 15,
    fontSize: FONT_SIZES.fifteen,
    fontFamily: Font_Family.semiBold,
    color: Colors.black,
  },
  cardContainer: {
    margin: 8,
    padding: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  itemRowStyles: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: Colors.grey,
    borderBottomWidth: 1,
  },
  itemInnerRow: {
    flexDirection: 'row',
    width: '45%',
    alignItems: 'center',
  },
  itemName: {
    fontFamily: Font_Family.regular,
    fontSize: FONT_SIZES.fifteen,
    marginLeft: 5,
    color: '#808080',
  },
  itemPriceBox: {
    width: '25%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemPrice: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.black,
  },
  qtyBox: {
    width: '30%',
    alignItems: 'flex-end',
  },
  qtyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,92,121,0.2)',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.primary,
    marginBottom: 10,
  },
  qty: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: 'black',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  addMoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 10,
  },
  rowStyles: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addMoreItemsText: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: 'black',
    paddingHorizontal: 10,
  },
  shadowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    elevation: 6,
    margin: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  couponHeading: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.secondary,
    paddingHorizontal: 10,
  },
  couponText: {
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.primary,
    paddingHorizontal: 10,
    marginTop: 5,
  },
  viewAllText: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.grey,
  },
  deliveryBox: {
    padding: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    elevation: 6,
    margin: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  cuponView: {
    // backgroundColor: Colors.white,
    height: 100,
    width: 150,
    borderRadius: 12,
    elevation: 6,
    margin: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  cuponImage: {
    height: '100%',
    width: '100%',
    borderRadius: 12,
  },
  deliveryInnerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  deliveryText: {
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.secondary,
    paddingHorizontal: 10,
  },
  changeText: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.grey,
  },
  addressText: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.black,
    paddingHorizontal: 30,
    marginTop: 5,
  },
  billSummary: {
    paddingTop: 15,
    fontSize: FONT_SIZES.fifteen,
    fontFamily: Font_Family.semiBold,
    color: Colors.black,
  },
  billBox: {
    margin: 8,
    padding: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  amountTitle: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.black,
  },
  amount: {
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.black,
  },
  grandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 15,
    borderTopColor: Colors.grey,
    borderTopWidth: 1,
  },
  grandTotalText: {
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.primary,
  },
  grandTotal: {
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.primary,
  },
  btnLabelStyles: {
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.white,
  },
  // Address---

  addressCard: {
    marginBottom: 15,
    width: '95%',
    alignSelf: 'center',
    padding: 15,
    borderRadius: 10,
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  titleStyles: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addressTitle: {
    color: Colors.black,
    fontFamily: Font_Family.regular,
    textTransform: 'capitalize',
  },
  addressBtn: {
    marginTop: 5,
    alignSelf: 'flex-end',
    fontFamily: Font_Family.medium,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.primary,
    textDecorationLine: 'underline',
  },
  // RazorPay

  payView: {
    backgroundColor: '#ffffff', 
    width: '35%',
    left:'15%',
    borderRadius: 4, 
    marginTop: -10, 
    shadowColor: '#000', 
    shadowOffset: {
      width: 0, height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 4,
    bottom:10
  },
  textLine: { height:1, width: '100%', borderWidth: 1, borderColor: Colors.primary },
  payText: { fontFamily: Font_Family.bold, textAlign: 'center', padding: 5, marginTop: 10,color:Colors.black,paddingBottom:10 }
});
