import {StyleSheet} from 'react-native';
import {Font_Family} from '../../../utils/Fontfamily';
import {FONT_SIZES} from '../../../utils/FontSize';
import {Colors} from '../../../utils/Colors';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white', paddingHorizontal: 10},
  inputStyles: {
    backgroundColor: 'white',
    width: '100%',
    alignSelf: 'center',
    marginVertical: 15,
  },
  recentSearches: {
    marginTop: 20,
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.thirteen,
    color: Colors.grey,
  },
  chipStyles: {
    marginRight: 10,
    backgroundColor: 'white',
    borderWidth: 2,
    borderRadius: 100,
    borderColor: Colors.grey,
    marginBottom: 10,
  },
  recommended: {
    marginTop: 20,
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.thirteen,
    color: Colors.grey,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginVertical: 10,
  },
  foodName: {
    marginRight: 10,
    backgroundColor: 'white',
    borderWidth: 2,
    borderRadius: 100,
    borderColor: Colors.grey,
    marginBottom: 10,
  },
  popularItems: {
    marginVertical: 20,
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.thirteen,
    color: Colors.black,
  },
  dishesText: {
    marginVertical: 10,
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.secondary,
  },
  seeMore: {
    marginVertical: 10,
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.primary,
    textAlign: 'right',
  },
  restaurantText: {
    marginBottom: 20,
    fontFamily: Font_Family.semiBold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.secondary,
  },
  //
  mainView: {
    backgroundColor: Colors.white,
    padding: 12,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 25,
  },
  adView: {
    backgroundColor: '#ccc',
    width: 20,
    height: 20,
    justifyContent: 'center',
    borderRadius: 5,
  },
  dishText: {
    fontSize: FONT_SIZES.eighteen,
    fontFamily: Font_Family.bold,
    textTransform: 'capitalize',
  },
  dishDetailText: {
    fontSize: FONT_SIZES.fifteen,
    fontFamily: Font_Family.medium,
    textTransform: 'capitalize',
  },
  dishDiscountText: {
    fontSize: FONT_SIZES.fifteen,
    fontFamily: Font_Family.medium,
    marginLeft: 10,
    color: Colors.grey,
  },
  dishRatingText: {
    fontSize: FONT_SIZES.thirteen,
    fontFamily: Font_Family.medium,
    marginLeft: 8,
    marginTop: '2%',
  },
  iconColor: {
    backgroundColor: Colors.green,
    borderRadius: 50,
    padding: 2,
    justifyContent: 'center',
    alignContent: 'center',
  },
  mainItemView: {
    flexDirection: 'row',
    marginTop: 5,
    borderWidth: 1,
    borderColor: Colors.secondary,
    borderRadius: 10,
    width: '100%',
    padding: 8,
  },
  itemImg: {
    height: 90,
    width: '100%',
  },
  itemImgSize: {
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.primary,
    width: '30%',
    height: '100%',
  },
  textBestSeller: {
    color: Colors.secondary,
    fontFamily: Font_Family.bold,
    fontSize: FONT_SIZES.tweleve,
    marginTop: '2%',
  },
  moreView: {
    borderWidth: 1,
    borderColor: Colors.grey,
    width: '50%',
    padding: 5,
    borderRadius: 20,
    flexDirection: 'row',
    marginTop: '10%',
  },
  moreText: {
    fontSize: FONT_SIZES.thirteen,
    color: Colors.grey,
    fontFamily: Font_Family.medium,
    marginTop: '2%',
  },
  addButton: {
    padding: 8,
    backgroundColor: Colors.white,
    bottom: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  addButtonText: {
    textAlign: 'center',
    fontFamily: Font_Family.bold,
    fontSize: FONT_SIZES.fifteen,
    color: Colors.green,
  },
});
