export const Font_Family = {
  regular: 'Metropolis-Regular',
  regularItalic: 'Metropolis-RegularItalic',
  bold: 'Metropolis-Bold',
  extraBold: 'Metropolis-ExtraBold',
  extraBoldItalic: 'Metropolis-ExtraBoldItalic',
  light: 'Metropolis-Light',
  lightItalic: 'Metropolis-LightItalic',
  medium: 'Metropolis-Medium',
  mediumItalic: 'Metropolis-MediumItalic',
  semiBold: 'Metropolis-SemiBold',
  semiBoldItalic: 'Metropolis-SemiBoldItalic',
  thin: 'Metropolis-Thin',
  thinItalic: 'Metropolis-ThinItalic',
};
