export const images = {
  google: require('../assets/auth/google.png'),
  backgroundImg: require('../assets/auth/LoginBg.png'),
  profile: require('../assets/auth/Profile.png'),
  momos: require('../assets/auth/momos.png'),
  kadaiPaneer: require('../assets/auth/chhole.png'),
  choleBhatoore: require('../assets/auth/choleBhatoore.png'),
  bannerImg: require('../assets/dashboardImages/bannerImage.png'),
  kadai_Paneer: require('../assets/dashboardImages/kadai_Paneer.png'),
  medal: require('../assets/dashboardImages/medal.png'),
  restaurant: require('../assets/dashboardImages/restaurant.jpg'),
  success: require('../assets/dashboardImages/success.png'),
  cuponCard: require('../assets/dashboardImages/cuponCard.png'),
  cuponCardImg: require('../assets/dashboardImages/cuponCardImg.png'),
  cuponImg: require('../assets/dashboardImages/cuponImg.png'),
  logo: require('../assets/dashboardImages/logo.png'),
};
